### ISSUE TITLE
Build throws error when dtproj.user file is not provided

### ISSUE THREAD

**Issue by pmalecka** [rtumaykin/ssis-build#14]
Hi Roman,

first of all: thanks for taking the time for writing this wonderful tool.

While giving it a test drive and comparing against the outputs of the Visual Studio Build, I noticed that the dtproj.user file is required - even if there are no parameters to be loaded from it.

Would it be possible to make this a non-mandatory file?

Thanks,
Peter

**Comment by rtumaykin** [comment]
Hi Peter, sorry for the long time it took me to get to this. I have implemented this change

**Comment by pmalecka** [comment]
Hi Roman,

thanks, I'll check it out!
